### ISSUE TITLE
Fails to find version: "version does not pass: 2.0.0 <= 0.0.0 > 2.1"

### ISSUE THREAD

**Issue by allanhvam** [HomecareHomebase/azcli-npm#8]
Version output from Azure CLI has change in the latest versions, so azcli-npm fails to find version.

Old version output:

C:\Users\abc>az --version
azure-cli (2.0.33)

acr (2.0.25)
acs (2.0.33)
advisor (0.5.1)
ams (0.1.1)
appservice (0.1.33)
backup (1.1.1)
batch (3.2.2)

Latest version output:

C:\Users\abc>az --version
azure-cli                         2.0.60

acr                                2.2.2
acs                               2.3.19
advisor                            2.0.0
ams                                0.4.2
appservice                        0.2.15
backup                             1.2.1
batch                              4.0.0

RegEx in index.ts validateVersion needs to be changed

**Comment by whilke** [comment]
Yikes! This needs to be done better. Thanks.

**Comment by whilke** [comment]
Thanks for the PR, this fix is now live in npm.

**Comment by allanhvam** [comment]
Did you build before publish? I am not seeing the change in https://unpkg.com/azcli-npm@1.1.6/dist/index.js

**Comment by whilke** [comment]
Thanks. Looks like the build pipeline was broken so it didn't pick up the changes with the publish. New version out that should be fixed.

**Comment by allanhvam** [comment]
Perfect, works now.
